// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfxaxuvteslmfefdeaje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmeGF4dXZ0ZXNsbWZlZmRlYWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTA1NDMsImV4cCI6MjA1NzYyNjU0M30.5PkXg41hHAkSmcDFYtef6s_DTJsGi726yJLxG3fp3kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);